In [1]:
import numpy as np

In [2]:
a = np.random.randn(5,5,5)

In [3]:
id a

SyntaxError: invalid syntax (<ipython-input-3-a3ab1612039a>, line 1)

In [4]:
id(a)

2949179232864

In [5]:
b=a

In [6]:
id(b)

2949179232864

In [7]:
b += 1

In [8]:
id(b)

2949179232864

In [9]:
id(a)

2949179232864

In [10]:
b

array([[[ 0.99456899, -0.34000332,  0.07527238,  0.73227561,
         -1.74045898],
        [ 1.71975443, -0.59369134,  1.36301949, -0.88597372,
          2.23879536],
        [ 1.38793366,  0.44556863,  1.60474512,  1.14014084,
          1.43269253],
        [ 0.73827114,  2.14054019,  0.86200046,  1.83046458,
          0.86686821],
        [ 2.08860773,  1.01987776,  2.12363545,  0.67613244,
         -0.64358191]],

       [[ 0.88907038,  1.01724304,  1.65573706, -1.36176498,
          1.1768193 ],
        [-0.67840212,  0.2060602 , -0.23694401,  2.54448465,
         -0.03494911],
        [ 0.72895175,  0.59576533,  1.62975034,  1.77653427,
          1.50037763],
        [ 2.59953433,  2.16393056, -0.32884672,  2.3887708 ,
          1.53739659],
        [ 0.0818112 ,  2.66489235,  0.99895009,  1.81820523,
         -0.15418539]],

       [[-0.8464357 ,  0.63446502,  1.71460446, -0.18490623,
          2.84024723],
        [ 2.48063026,  2.69579247,  1.09164788,  0.4473386 ,
         -0

In [11]:
a

array([[[ 0.99456899, -0.34000332,  0.07527238,  0.73227561,
         -1.74045898],
        [ 1.71975443, -0.59369134,  1.36301949, -0.88597372,
          2.23879536],
        [ 1.38793366,  0.44556863,  1.60474512,  1.14014084,
          1.43269253],
        [ 0.73827114,  2.14054019,  0.86200046,  1.83046458,
          0.86686821],
        [ 2.08860773,  1.01987776,  2.12363545,  0.67613244,
         -0.64358191]],

       [[ 0.88907038,  1.01724304,  1.65573706, -1.36176498,
          1.1768193 ],
        [-0.67840212,  0.2060602 , -0.23694401,  2.54448465,
         -0.03494911],
        [ 0.72895175,  0.59576533,  1.62975034,  1.77653427,
          1.50037763],
        [ 2.59953433,  2.16393056, -0.32884672,  2.3887708 ,
          1.53739659],
        [ 0.0818112 ,  2.66489235,  0.99895009,  1.81820523,
         -0.15418539]],

       [[-0.8464357 ,  0.63446502,  1.71460446, -0.18490623,
          2.84024723],
        [ 2.48063026,  2.69579247,  1.09164788,  0.4473386 ,
         -0

In [12]:
b += 1
b

array([[[ 1.99456899,  0.65999668,  1.07527238,  1.73227561,
         -0.74045898],
        [ 2.71975443,  0.40630866,  2.36301949,  0.11402628,
          3.23879536],
        [ 2.38793366,  1.44556863,  2.60474512,  2.14014084,
          2.43269253],
        [ 1.73827114,  3.14054019,  1.86200046,  2.83046458,
          1.86686821],
        [ 3.08860773,  2.01987776,  3.12363545,  1.67613244,
          0.35641809]],

       [[ 1.88907038,  2.01724304,  2.65573706, -0.36176498,
          2.1768193 ],
        [ 0.32159788,  1.2060602 ,  0.76305599,  3.54448465,
          0.96505089],
        [ 1.72895175,  1.59576533,  2.62975034,  2.77653427,
          2.50037763],
        [ 3.59953433,  3.16393056,  0.67115328,  3.3887708 ,
          2.53739659],
        [ 1.0818112 ,  3.66489235,  1.99895009,  2.81820523,
          0.84581461]],

       [[ 0.1535643 ,  1.63446502,  2.71460446,  0.81509377,
          3.84024723],
        [ 3.48063026,  3.69579247,  2.09164788,  1.4473386 ,
          0

In [13]:
a

array([[[ 1.99456899,  0.65999668,  1.07527238,  1.73227561,
         -0.74045898],
        [ 2.71975443,  0.40630866,  2.36301949,  0.11402628,
          3.23879536],
        [ 2.38793366,  1.44556863,  2.60474512,  2.14014084,
          2.43269253],
        [ 1.73827114,  3.14054019,  1.86200046,  2.83046458,
          1.86686821],
        [ 3.08860773,  2.01987776,  3.12363545,  1.67613244,
          0.35641809]],

       [[ 1.88907038,  2.01724304,  2.65573706, -0.36176498,
          2.1768193 ],
        [ 0.32159788,  1.2060602 ,  0.76305599,  3.54448465,
          0.96505089],
        [ 1.72895175,  1.59576533,  2.62975034,  2.77653427,
          2.50037763],
        [ 3.59953433,  3.16393056,  0.67115328,  3.3887708 ,
          2.53739659],
        [ 1.0818112 ,  3.66489235,  1.99895009,  2.81820523,
          0.84581461]],

       [[ 0.1535643 ,  1.63446502,  2.71460446,  0.81509377,
          3.84024723],
        [ 3.48063026,  3.69579247,  2.09164788,  1.4473386 ,
          0

In [14]:
id(a[:, :, 0])

2949179341680

In [15]:
c = a[:, :, 0]

In [16]:
id(c)

2949179340240

In [17]:
id(a[0:2][0:2][0:2])

2949179381360

In [18]:
d = a[0:2][0:2][0:2]

In [19]:
id(d)

2949179383280